# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
    - tlmgr install collection-latexrecommended
    - tlmgr install collection-fontsrecommended
    - tlmgr install bbm

language: R
cache: packages
branches:
  only:
  - master 

warnings_are_errors: false
r_build_args: ' --resave-data --compact-vignettes="both" '

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr);   codecov(line_exclusions=list("R/S4.R" = c(20:28,33:41),"R/Arith.R"=6:7,"R/matrix.R"=96))'
  
  