# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
    - tlmgr install collection-latexrecommended
    - tlmgr install collection-fontsrecommended
    - tlmgr install letltxmacro
    - tlmgr install bbm

language: R
cache: packages
branches:
  only:
  - master 

env:
   global:
     - R_BUILD_ARGS: '--resave-data --compact-vignettes="both" '
     
