# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
    - tlmgr install collection-latexrecommended
    - tlmgr install collection-fontsrecommended
    - tlmgr install letltxmacro
    - tlmgr install bbm

language: R
cache: packages
branches:
  only:
  - master 

warnings_are_errors: true
r_build_args: ' --resave-data --compact-vignettes="both" '

