/* This generated by running     

tools::package_native_routine_registration_skeleton(".") 


at the R command line

*/

#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* FIXME: 
   Check these declarations against the C/Fortran source code.
*/

/* .C calls */
extern void octonion_prod(void *, void *, void *, void *);
extern void quaternion_prod(void *, void *, void *, void *);

static const R_CMethodDef CEntries[] = {
    {"octonion_prod",   (DL_FUNC) &octonion_prod,   4},
    {"quaternion_prod", (DL_FUNC) &quaternion_prod, 4},
    {NULL, NULL, 0}
};

void R_init_onion(DllInfo *dll)
{
    R_registerRoutines(dll, CEntries, NULL, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
